- import_role:
    name: workspace

# Download kubectl command
- name: Download kubectl command
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/kubectl
    dest: "{{ rancher_bin }}/kubectl"
    mode: 0744


