- name: Clean up older artifacts
  file:
    state: absent
    path: "{{ rancher_bin }}/"
  when: is_upgrade is defined and is_upgrade == true

# Create common directories
- name: Create Rancher workplace directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.type }}"
  with_items:
    - { path: "{{ rancher_snapshots }}", type: directory }
    - { path: "{{ rancher_workspace }}" , type: directory }
    - { path: "{{ rancher_bin }}" , type: directory }
    - { path: "{{ image_workspace }}", type: directory }

# Make ssh key mode to be 600
- name: Make ssh key mode to be 600
  file:
    path: "{{ ansible_ssh_private_key_file }}"
    state: file
    mode: 0600