---

- name: Update Helm repos
  shell: |
      set -e
      helm init --client-only
      helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
      helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
      helm repo update

- name: Install cert-manager
  shell: |
      set -e
      rm -rf cert-manager-*.tgz
      rm -rf cert-manager      
      helm fetch stable/cert-manager  --version {{ cert_manager_version }}
      helm template ./cert-manager-*.tgz --output-dir . \
          --name cert-manager --namespace kube-system \
          --set image.repository={{ default_docker_registry }}/quay.io/jetstack/cert-manager-controller
      kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml
      kubectl label --overwrite namespace kube-system certmanager.k8s.io/disable-validation=true
      kubectl -n kube-system apply -R -f ./cert-manager
      sleep 100s
  args:
    chdir: "{{ rancher_workspace }}"

- name: Install Rancher console
  shell: |
      set -e
      rm -rf rancher
      rm -rf rancher-*.tgz

      ns=`kubectl get ns|grep cattle-system|wc -l`
      if [ "$ns" -eq "0" ]; then
         kubectl create ns cattle-system
      fi

      helm fetch {{ rancher_chart_repo }}/rancher --version {{ rancher_chart_version }}
      helm template rancher-*.tgz --output-dir . --is-upgrade \
          --name rancher --namespace cattle-system \
          --set hostname={{ rancher_hostname }} --set rancherImage={{ default_docker_registry }}/rancher/rancher
      kubectl -n cattle-system apply -R -f rancher
  args:
    chdir: "{{ rancher_workspace }}"

